# 🐼 Pandas

### Learning Data Analysis Step by Step

---

> **What you will learn:** How to load, explore, and clean real data using Pandas  
> **Dataset:** Student Lifestyle & Exam Performance (1,150 students)  
> **Tip:** Run each cell one at a time. Read the explanation, then look at the output.

---

## 📜 What is Pandas — and Where Did It Come From?

In **2008**, a programmer named **Wes McKinney** was working at a finance company in New York. Every day he had to analyse huge tables of data — stock prices, economic numbers, reports.

The tools available at the time were painful to use for this kind of work. So Wes built his own — and called it **pandas**.

The name comes from **"panel data"**, an economics term for data tracked over time. It also stands for **"Python Data Analysis"**.

He released it for free in **2009**. Today it is downloaded **100 million times every month** and used by Google, Netflix, NASA, and almost every data team in the world.

---

# 📊 Introduction to Pandas

## 📌 What is Pandas?

Pandas is a powerful Python library used for **data analysis and data manipulation**.  
It provides easy-to-use data structures for handling structured data like tables.

---

## 📌 Key Data Structures

- **Series** → 1D labeled array (like a column)
- **DataFrame** → 2D table (rows and columns, like Excel sheet)

---

## 📌 Key Features of Pandas

- **Easy data handling** → Load, clean, and process data efficiently
- **Data alignment** → Automatically aligns data by labels
- **Handling missing data** → Provides functions to detect and fill missing values
- **Filtering & selection** → Easily select specific rows and columns
- **Grouping & aggregation** → Perform operations like sum, mean, count
- **Merging & joining** → Combine multiple datasets
- **Time series support** → Work with date and time data
- **File handling** → Read/write data from CSV, Excel, JSON, HTML, SQL etc.

---

## 📌 Why Use Pandas?

- Simplifies complex data operations
- Saves time compared to manual coding
- Widely used in Data Science and AI

---

## 📌 Applications in AI

- Data preprocessing
- Cleaning datasets
- Feature selection
- Preparing data for machine learning models

---

## 🤔 Why Do We Need Pandas?

Imagine you have a spreadsheet with 1,000 student records. You want to:

- Find all students who scored above 80
- Calculate the average score by gender
- Fix typos in the data

In plain Python you would write 30+ lines of code and loops.

With Pandas, each of those tasks is **one line**.

---

## 🏗️ The Two Main Building Blocks

**Series** → a single column of data (like one column in Excel)

```
0    85
1    72
2    91
3    68
```

**DataFrame** → a full table with rows and columns (like an entire Excel sheet)

```
   name   age  score
0  Alice   21     85
1  Bob     19     72
2  Carol   22     91
```

Everything we do in Pandas works with these two objects.

---
# Part 1 — Getting Started
---

### Step 1 — Import Pandas

Before using Pandas we need to import it. We give it the short nickname `pd` — this is the standard convention used by everyone in the world.

In [1]:
import pandas as pd

### Step 2 — Check the Version

Let's confirm Pandas is installed and see which version we have.

In [2]:
pd.__version__

'3.0.3'

### Step 3 — Create Your First Series

A **Series** is like a single list of values with labels (index) on the side. Think of it as one column of a spreadsheet.

In [ ]:
country = ["pakistan", "india", "nepal", "USA"]
# pd.Series(country)

In [111]:
# A simple series of exam scores
scores = pd.Series([85, 72, 91, 68, 95])
scores

0    85
1    72
2    91
3    68
4    95
dtype: int64

### Step 4 — Series with Custom Labels

Instead of numbers (0, 1, 2...) we can use names as the index.

In [118]:
# Give each score a student name as the label
scores = pd.Series([85, 72, 91, 68, 95],
    index=['Ali', 'Sara', 'John', 'Sana', 'Bilal'],
    name = "students marks"
)
scores

Ali      85
Sara     72
John     91
Sana     68
Bilal    95
Name: students marks, dtype: int64

#### Series from dict

### Step 5 — Access One Value from a Series

Use the label (or position number) to get a single value.

In [119]:
# Get Ali's score by name
scores['Ali']

np.int64(85)

### Step 6 — Basic Math on a Series

Pandas does math on all values at once — no need to write a loop.

In [5]:
# Average score
scores = pd.Series(
    [85, 72, 91, 68, 95],
    index=['Ali', 'Sara', 'John', 'Sana', 'Bilal']
)
scores.mean()

np.float64(82.2)

In [6]:
# Highest score
scores.max()

np.int64(95)

In [7]:
# Who scored above 80?
scores[scores > 80]

Ali      85
John     91
Bilal    95
dtype: int64

#### Attributes of Series

In [9]:
# size 
scores = pd.Series(
    [85, 72, 91, 68, 95],
    index=['Ali', 'Sara', 'John', 'Sana', 'Bilal']
)
scores.size

5

In [10]:
# dtype
scores = pd.Series(
    [85, 72, 91, 68, 95],
    index=['Ali', 'Sara', 'John', 'Sana', 'Bilal']
)
scores.dtype

dtype('int64')

In [ ]:
# name
marks =[85, 72, 91, 68, 95]
scores = pd.Series(marks,
    index=['Ali', 'Sara', 'John', 'Sana', 'Bilal'], name= "Marks of Students"
)
scores.name

'Marks of Students'

In [16]:
# is_unique
scores.is_unique

True

In [17]:
# index
scores.index

Index(['Ali', 'Sara', 'John', 'Sana', 'Bilal'], dtype='str')

In [19]:
# value
scores.values

array([85, 72, 91, 68, 95])

### Step 7 — Create Your First DataFrame

A **DataFrame** is a full table — like an Excel spreadsheet. We build it from a dictionary where each key is a column name and each value is a list of data.

In [42]:
# using list

In [46]:
# using dict

In [121]:
# Create a small student table
data = {
    'name'        : ['Ali', 'Sara', 'John', 'Sana', 'Bilal'],
    'age'         : [21, 19, 22, 20, 21],
    'study_hours' : [5.5, 3.0, 7.2, 2.1, 6.8],
    'exam_score'  : [85, 72, 91, 68, 95]
}

students = pd.DataFrame(data)
students

    name  age  study_hours  exam_score
0    Ali   21          5.5          85
1   Sara   19          3.0          72
2   John   22          7.2          91
3   Sana   20          2.1          68
4  Bilal   21          6.8          95

### Step 8 — Get One Column from a DataFrame

Use square brackets with the column name, just like looking up a key in a dictionary.

In [125]:
students[["age", "name"]]

   age   name
0   21    Ali
1   19   Sara
2   22   John
3   20   Sana
4   21  Bilal

In [ ]:
# Get the exam_score column
students[["exam_score", "age", "name"]]

0    85
1    72
2    91
3    68
4    95
Name: exam_score, dtype: int64

### Step 9 — Get Multiple Columns

Pass a **list** of column names inside the brackets.

In [9]:
# Get name and exam_score columns only
students[['name', 'exam_score', "age"]]

    name  exam_score  age
0    Ali          85   21
1   Sara          72   19
2   John          91   22
3   Sana          68   20
4  Bilal          95   21

---
# Part 2 — Loading Real Data
---

Now we move to our **real dataset** — 1,150 student records with messy, real-world data quality issues. This is what data actually looks like in the real world.

**Dataset columns:**

- Student ID, Age, Gender
- Study hours, Social media hours, Netflix hours
- Sleep hours, Attendance, Exercise frequency
- Diet quality, Internet quality, Mental health rating
- Part-time job, Parental education, Extracurricular activities
- **Exam Score** (what we want to understand!)

### Step 10 — Load the CSV File

`pd.read_csv()` reads a CSV file and turns it into a DataFrame automatically.

In [126]:
df1 = pd.read_csv('Messy_student_data.csv')
df1

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [1]:
import pandas as pd

In [11]:
# Load the dataset
# Make sure Messy_student_data.csv is in the same folder as this noteb
df_raw = pd.read_csv('Messy_student_data.csv')

### Step 11 — Make a Copy to Work On

Always keep the original raw data untouched. Work on a copy so you can always go back if something goes wrong.

In [136]:
# Work on this copy — never touch df_raw
df = df_raw.copy()

---
# Part 3 — Exploring the Data

Before cleaning or analysing anything, we need to **look at and understand** the data. This is always the first step.
---

### Step 12 — See the First 5 Rows

`head()` shows the first few rows. It is the quickest way to see what your data looks like.

In [135]:
df.sample(5)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
552,NaN,19.405530,female,0.2,9.280540,0.530506,Yes,76.648996,4.740294744203405,unknown,1.452090,Master,Good,4.309979,Yes,37.494881,1971
373,NaN,28.429795,male,NaN,0.977640,5.143002,No,73.269867,6.5073888225367895,NaN,4.626630,Bachelor,Good,7.704352,Yes,70.792603,4446
684,S1684,20.029184,MALE,3.7,0.841874,1.736078,No,NaN,3.4764091951527254,Fair,1.111116,Bachelor,Good,0.764651,Yes,301.026813,2258
480,S1480,NaN,MALE,NaN,NaN,-3.035657,Yes,77.807729,7.912772686109696,Good,11.743823,NaN,Good,-4.916391,NaN,52.795160,1923
734,S1734,24.345945,femle,3.4,-0.654037,2.700388,No,106.282568,7.660100294074727,NaN,5.173253,Bachelor,NaN,2.024706,No,70.924659,4494

In [5]:
# df_raw = pd.read_csv('Messy_student_data.csv')
# df = df_raw.copy()
df.head(10)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
5,S1005,23.193687,male,7.2,0.762742,4.156124,No,82.212347,NaN,Fair,-1.725755,Master,Average,4.610438,No,106.436337,1863
6,S1006,22.062970,femle,5.6,-0.033797,-3.916967,Yes,NaN,-4.759269743,Good,-3.266879,Master,Poor,2.176012,No,93.537529,4953
7,S1007,NaN,NaN,4.3,-0.912870,3.373847,Yes,76.041926,3.109453671639383,Fair,NaN,Bachelor,Average,4.307425,No,365.927950,2313
8,S1008,NaN,female,NaN,3.663144,6.903434,No,99.326218,4.4,Good,4.314662,NaN,Good,NaN,No,80.297148,5120
9,S1009,23.669075,FEMALE,4.8,5.199887,-0.088103,No,96.742474,7.054294851537139,Good,2.072327,Bachelor,NaN,11.481817,Yes,100.123883,2126

### Step 13 — See the Last 5 Rows

`tail()` shows the last few rows. Useful to check that the data ends properly.

In [12]:
df.tail(3)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

### Step 14 — See a Random Sample

`sample()` picks random rows. Great for getting a feel for the data without always seeing the same rows.

In [138]:
df.sample(10)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
532,S1532,14.114549,male,4.8,3.992352,4.606972,Yes,NaN,NaN,Fair,7.206016,High School,Good,5.055502,Yes,82.817721,7184
54,S1054,22.887493,F,3.1,4.750201,4.234454,Yes,62.898911,8.123914597732114,Fair,1.046398,High School,Good,NaN,No,68.988148,3594
377,S1377,18.375337,F,ten,0.117138,5.569018,No,92.398634,9.147625677156988,Good,3.094760,High School,NaN,-0.993806,Yes,68.157373,4105
1109,S1459,19.842781,femle,ten,4.676542,-0.352078,Yes,94.377539,5.006968893712664,Poor,-3.886722,High School,Good,4.660478,No,77.638547,5103
930,S1927,16.665809,female,3.3,2.536820,1.714756,No,69.844672,2.697038322992454,Good,0.198855,Bachelor,Good,0.885961,No,39.430142,3510
752,S1752,9.558960,M,4.5,2.573508,2.309560,Yes,71.879279,3.036875411888123,Good,1.670908,High School,Good,6.431041,Yes,71.010669,7873
607,S1607,17.578600,F,3.2,3.629595,NaN,No,82.035366,8.293514121820708,Poor,0.173749,Bachelor,NaN,5.315392,Yes,55.032147,1693
354,S1354,19.193603,male,-9.025736001,9.555948,6.695513,No,100.267642,ten,unknown,3.777069,High School,NaN,0.804976,No,45.964581,1561
747,S1747,24.945650,male,1.8,-0.376953,-2.370344,No,82.896558,9.61272324793348,Good,-1.807033,High School,NaN,10.636501,No,46.280352,3915
961,S1958,15.938143,MALE,0,6.094525,10.189007,Yes,88.450871,2.0404068227293672,Good,2.503396,High School,Average,2.467641,No,29.080771,4631

### Step 15 — Check the Size of the Data

`shape` tells us how many **rows** and **columns** we have. It returns `(rows, columns)`.

In [76]:
df.shape

(1153, 17)

### Step 16 — See All Column Names

`columns` lists every column name. Notice that some have **trailing spaces** — this will cause bugs later!

In [20]:
df.columns

Index(['student_id ', 'age ', 'GENDER', 'STUDY_HOURS_PER_DAY',
       'SOCIAL_MEDIA_HOURS', 'netflix_hours ', 'PART_TIME_JOB',
       'attendance_percentage ', 'SLEEP_HOURS', 'diet_quality ',
       'EXERCISE_FREQUENCY', 'PARENTAL_EDUCATION_LEVEL', 'INTERNET_QUALITY',
       'mental_health_rating ', 'EXTRACURRICULAR_PARTICIPATION', 'EXAM_SCORE',
       'RANDOM_ID'],
      dtype='str')

### Step 17 — Get a Full Overview with info()

`info()` is one of the most useful commands. It shows:

- Column names
- How many non-null (non-missing) values each column has
- The data type of each column

Look for columns where **non-null count is less than 1150** — those have missing values.

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1153 entries, 0 to 1152
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1032 non-null   str
 1   age                            1041 non-null   float64
 2   GENDER                         1039 non-null   str
 3   STUDY_HOURS_PER_DAY            998 non-null    str
 4   SOCIAL_MEDIA_HOURS             1044 non-null   float64
 5   netflix_hours                  1032 non-null   float64
 6   PART_TIME_JOB                  1032 non-null   str
 7   attendance_percentage          1039 non-null   float64
 8   SLEEP_HOURS                    1044 non-null   str
 9   diet_quality                   1047 non-null   str
 10  EXERCISE_FREQUENCY             1042 non-null   float64
 11  PARENTAL_EDUCATION_LEVEL       947 non-null    str
 12  INTERNET_QUALITY               1043 non-null   str
 13  mental_health_rating           1041 non-null   float64
 14  EXTRACURRICULAR_PARTICIPATION  1039 non-null   str
 15  EXAM_SCORE                     1039 non-null   float64
 16  RANDOM_ID                      1153 non-null   int64
dtypes: float64(7), int64(1), str(9)
memory usage: 153.3 KB

### Step 18 — Get Basic Statistics with describe()

`describe()` gives statistics for all numeric columns:

- **count** = how many non-missing values
- **mean** = average
- **std** = how spread out the values are
- **min / max** = smallest and largest value
- **25% / 50% / 75%** = quartiles

⚠️ Look at the min values — some are **negative**, which is impossible for hours!

In [23]:
df.describe()

,age,SOCIAL_MEDIA_HOURS,netflix_hours,attendance_percentage,EXERCISE_FREQUENCY,mental_health_rating,EXAM_SCORE,RANDOM_ID
count,1041.000000,1044.000000,1032.000000,1039.000000,1042.000000,1041.000000,1039.000000,1153.000000
mean,20.429438,2.651652,2.011406,83.906115,2.958623,5.379768,83.807246,5539.029488
std,3.776914,3.244181,3.285012,9.713085,3.603461,4.179635,66.490540,2648.087879
min,9.558960,-8.078218,-9.915100,55.726353,-9.503038,-5.626254,20.223173,1002.000000
25%,17.668028,0.507419,-0.211819,77.715425,0.416286,2.408725,58.843359,3240.000000
50%,20.496321,2.611274,1.937920,83.959410,3.046520,5.390964,71.034216,5530.000000
75%,23.018131,4.788802,4.275851,91.018567,5.355855,8.245798,83.926080,7808.000000
max,31.463841,12.334267,12.414241,106.282568,14.645852,18.141586,502.824692,9993.000000

### Step 19 — Count Missing Values

`isnull()` checks every cell — True if missing, False if not.  
`.sum()` counts the True values per column.  
This tells us exactly how many values are missing in each column.

In [142]:
df.isnull().sum()

student_id                       121
age                              112
GENDER                           114
STUDY_HOURS_PER_DAY              155
SOCIAL_MEDIA_HOURS               109
netflix_hours                    121
PART_TIME_JOB                    121
attendance_percentage            114
SLEEP_HOURS                      109
diet_quality                     106
EXERCISE_FREQUENCY               111
PARENTAL_EDUCATION_LEVEL         206
INTERNET_QUALITY                 110
mental_health_rating             112
EXTRACURRICULAR_PARTICIPATION    114
EXAM_SCORE                       114
RANDOM_ID                          0
dtype: int64

In [22]:
df.isnull().sum()

student_id                       121
age                              112
GENDER                           114
STUDY_HOURS_PER_DAY              155
SOCIAL_MEDIA_HOURS               109
netflix_hours                    121
PART_TIME_JOB                    121
attendance_percentage            114
SLEEP_HOURS                      109
diet_quality                     106
EXERCISE_FREQUENCY               111
PARENTAL_EDUCATION_LEVEL         206
INTERNET_QUALITY                 110
mental_health_rating             112
EXTRACURRICULAR_PARTICIPATION    114
EXAM_SCORE                       114
RANDOM_ID                          0
dtype: int64

### Step 20 — Count Duplicate Rows

`duplicated()` marks rows that are exact copies of another row.  
`.sum()` counts how many duplicates exist.

In [146]:
df.duplicated().sum()

np.int64(3)

In [150]:
df[df.duplicated(keep=False)]    #keep=False

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
873,S1873,17.648301,F,4.3,NaN,-3.233988,No,82.252457,-0.489389156,Fair,7.483958,High School,Good,10.956222,No,84.367479,8136
874,S1874,16.940867,M,5.1,2.731454,0.307086,No,95.648970,8.048016356998517,unknown,2.259864,Master,Average,9.087426,No,96.000869,9779
875,S1875,20.513999,femle,7.6,2.040626,NaN,NaN,93.904316,6.40760898746424,Poor,-0.507753,High School,Good,7.078776,NaN,98.565704,7398
876,S1873,17.648301,F,4.3,NaN,-3.233988,No,82.252457,-0.489389156,Fair,7.483958,High School,Good,10.956222,No,84.367479,8136
877,S1874,16.940867,M,5.1,2.731454,0.307086,No,95.648970,8.048016356998517,unknown,2.259864,Master,Average,9.087426,No,96.000869,9779
878,S1875,20.513999,femle,7.6,2.040626,NaN,NaN,93.904316,6.40760898746424,Poor,-0.507753,High School,Good,7.078776,NaN,98.565704,7398

In [ ]:
# # rename
df.rename(columns={"GENDER": "gender"})  #inplace = True

,student_id,age,gender,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [152]:
df.head(1)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.1535,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342

### Step 21 — Check Unique Values in a Column

`value_counts()` shows all unique values in a column and how many times each appears.

Look at the GENDER column — we should only have Male, Female, Other. But notice how many messy variations exist!

In [157]:
df['GENDER'].value_counts(dropna=False)

GENDER
NaN         114
MALE        103
 F           99
mle          91
female       89
 M           81
male         79
femle        69
FEMALE       67
 female      53
 male        46
 femle       43
  F          39
 mle         36
 FEMALE      35
 MALE        35
Other        34
  M          30
 Other       10
Name: count, dtype: int64

## Question:

1. Create a Pandas Series from the following list:
   - [85, 92, 78, 95, 88]
   - Display the Series.

2. Create a Series of student names:
   - ["Ali", "Sara", "Ahmed", "Ayesha", "Sana"]
   - Assign custom indexes:
   - 101, 102, 103, 104, 105

3. Create a Series from the dictionary:
   - Display the Series.
4. Create the Series:
   - Perform the following:
   - Display the size.
   - Display the shape.
   - Display the index.
   - Display the data type.
   - Check whether the indexes are unique.

5. Create a Series of five city names.
   - Perform the following:
   - Display the first three values.
   - Display the last two values.
   - Display the total number of values.

6. Load the CSV file and perform the following operations:
   - Display the first 5 rows.
   - Display the last 3 rows.
   - Display the shape.
   - Display the size.
   - Display all column names.
   - Display data types.
   - Display statistical summary.
   - Check for missing values.
   - Check for duplicate rows.

## Maths Methods

In [ ]:
df.sum()   #axis = 1

student_id                       S1000S1001S1002S1003S1004S1005S1006S1007 S1008...
age                                                                   21267.045193
gender                           femleFEMALEMALE  F   FEMALE male femle  female...
STUDY_HOURS_PER_DAY              0tenten7.25.64.34.84.6tenten3.42.41tenten1.83....
SOCIAL_MEDIA_HOURS                                                      2768.32505
netflix_hours                                                           2075.77118
PART_TIME_JOB                    NoNoNo No NoNoYesYesNo No  No  Yes  No NoNoNoN...
attendance_percentage                                                 87178.453886
SLEEP_HOURS                      7.2941227927551061.7116124200265550.2453070425...
diet_quality                     FairGoodPoor Poor FairFair Good  Fair GoodGood...
EXERCISE_FREQUENCY                                                     3082.884811
PARENTAL_EDUCATION_LEVEL          Master  High School  Master MasterMasterMaste...
INTERNET_QUALITY                 Average Poor Good Average Poor Average Good Go...
mental_health_rating                                                   5600.338292
EXTRACURRICULAR_PARTICIPATION    Yes No NoYesNoNoNo No No Yes NoNoNoNo No NoYes...
EXAM_SCORE                                                            87075.728994
RANDOM_ID                                                                  6386501
dtype: object

In [ ]:
# mean
# min 
# max
# median
# std
# var

## Selecting Row from the Data Fram

- iloc - searches using index positions
- loc - searches using index labels

In [176]:
data = {
    'name'        : ['Ali', 'Sara', 'John', 'Sana', 'Bilal',"Noor"],
    'age'         : [21, 19, 22, 20, 21,22],
    'study_hours' : [5.5, 3.0, 7.2, 2.1, 6.8,5.9],
    'exam_score'  : [85, 72, 91, 68, 95, 97]
}

students = pd.DataFrame(data)
# students = students.set_index('name')
students

    name  age  study_hours  exam_score
0    Ali   21          5.5          85
1   Sara   19          3.0          72
2   John   22          7.2          91
3   Sana   20          2.1          68
4  Bilal   21          6.8          95
5   Noor   22          5.9          97

In [ ]:
# print(students.iloc[1])
# # print(students.iloc[4])

print(students.iloc[0:7:3])

print(students.iloc[[0,5,4,2,3]])

   name  age  study_hours  exam_score
0   Ali   21          5.5          85
3  Sana   20          2.1          68
    name  age  study_hours  exam_score
0    Ali   21          5.5          85
5   Noor   22          5.9          97
4  Bilal   21          6.8          95
2   John   22          7.2          91
3   Sana   20          2.1          68

In [179]:
data = {
    'name'        : ['Ali', 'Sara', 'John', 'Sana', 'Bilal'],
    'age'         : [21, 19, 22, 20, 21],
    'study_hours' : [5.5, 3.0, 7.2, 2.1, 6.8],
    'exam_score'  : [85, 72, 91, 68, 95]
}

students = pd.DataFrame(data)
# students = students.set_index('name')
students

    name  age  study_hours  exam_score
0    Ali   21          5.5          85
1   Sara   19          3.0          72
2   John   22          7.2          91
3   Sana   20          2.1          68
4  Bilal   21          6.8          95

In [175]:
# print(students.loc["Ali"])
# print(students.loc["Ali":"Sana":2])


print(students.loc[["Ali","Sana","Sara"]])

      age  study_hours  exam_score
name
Ali    21          5.5          85
Sana   20          2.1          68
Sara   19          3.0          72

### Selecting both rows and cols

In [178]:
students

    name  age  study_hours  exam_score
0    Ali   21          5.5          85
1   Sara   19          3.0          72
2   John   22          7.2          91
3   Sana   20          2.1          68
4  Bilal   21          6.8          95
5   Noor   22          5.9          97

In [ ]:

students.iloc[0:2, 0:3]

   name  age  study_hours
0   Ali   21          5.5
1  Sara   19          3.0

In [145]:
students.loc["Ali":"John","age":"study_hours"]

      age  study_hours
name
Ali    21          5.5
Sara   19          3.0
John   22          7.2

---
# Part 4 — Cleaning the Data

Real data is almost always messy. Before we analyse it, we must fix it.

Here are the problems we found in our dataset:

| Problem | Example |
|---------|--------|
| Column names have spaces | `'student_id '` instead of `'student_id'` |
| Inconsistent casing | Some columns are UPPERCASE, others lowercase |
| Duplicate rows | Same student appears twice |
| Useless column | `RANDOM_ID` has no meaning |
| Missing values | Many columns have NaN (blank) cells |
| Gender typos | `'femle'`, `'mle'`, `' FEMALE '` all mean different things to pandas |
| Text instead of numbers | `'ten'` written as a word in a numeric column |
| Negative hours | `-3.5` hours of Netflix is impossible |
| Exam scores > 100 | A score of 365 is impossible |

We will fix each one step by step.

---

### Step 22 — Fix Column Names (Remove Spaces)

Some column names have hidden spaces at the start or end. This causes bugs like `df['student_id']` giving a KeyError even though you can see the column.

`str.strip()` removes spaces from both ends.  
`str.lower()` makes everything lowercase — so all column names are consistent.

In [186]:
df.columns= df.columns.str.strip().str.lower()
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714

In [142]:
# Remove spaces and make all column names lowercase
df.columns = df.columns.str.strip().str.lower()
# Verify — all clean now
print(df.columns)
# print(df.head())

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score',
       'random_id'],
      dtype='str')

**Fix Text Numbers in Numeric Columns**

The `study_hours_per_day` and `sleep_hours` columns are supposed to be numbers, but some entries have the word `'ten'` instead of `10`.

`replace()` swaps the text for the correct number string.  
`pd.to_numeric()` then converts the whole column to a proper number type.  
`errors='coerce'` means: if anything still can't be converted, make it NaN instead of crashing.

In [75]:
df.sample(5)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
1135,S1760,23.355860,mle,0.5,5.461359,4.023753,Yes,79.225983,8.807546682322858,Good,NaN,NaN,Average,6.369022,Yes,30.258788,2805
265,NaN,10.964141,F,0.6,4.545314,5.908331,No,NaN,3.538192652063397,Good,3.033991,Bachelor,Good,NaN,No,20.223173,7192
340,NaN,14.447865,male,4.7,0.695067,5.061576,Yes,71.073024,8.457538694867276,Fair,5.749208,Bachelor,Good,NaN,No,82.279440,7780
427,S1427,28.635489,femle,ten,3.936608,-4.111219,Yes,77.358642,11.198937407806227,NaN,2.695206,Bachelor,Good,NaN,No,73.433529,6246
461,NaN,23.252820,NaN,ten,6.296579,2.328705,No,93.125740,5.453939529177829,Fair,7.825391,NaN,NaN,5.362926,No,NaN,9053

In [72]:
df["study_hours_per_day"].replace("ten", "10")

0         0
1       NaN
2       NaN
3        10
4        10
       ...
1148      0
1149    NaN
1150    3.8
1151    1.3
1152    4.1
Name: study_hours_per_day, Length: 1153, dtype: str

In [189]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1153 entries, 0 to 1152
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1032 non-null   str
 1   age                            1041 non-null   float64
 2   gender                         1039 non-null   str
 3   study_hours_per_day            998 non-null    str
 4   social_media_hours             1044 non-null   float64
 5   netflix_hours                  1032 non-null   float64
 6   part_time_job                  1032 non-null   str
 7   attendance_percentage          1039 non-null   float64
 8   sleep_hours                    1044 non-null   str
 9   diet_quality                   1047 non-null   str
 10  exercise_frequency             1042 non-null   float64
 11  parental_education_level       947 non-null    str
 12  internet_quality               1043 non-null   str
 13  mental_health_rating           1041 non-null   float64
 14  extracurricular_participation  1039 non-null   str
 15  exam_score                     1039 non-null   float64
 16  random_id                      1153 non-null   int64
dtypes: float64(7), int64(1), str(9)
memory usage: 153.3 KB

In [ ]:
df["study_hours_per_day"]=df["study_hours_per_day"].replace("ten", "10") 

# df["study_hours_per_day"].astype(int)

ValueError: cannot convert float NaN to integer

In [191]:
df["study_hours_per_day"]= pd.to_numeric(df["study_hours_per_day"], errors="coerce")

In [80]:
# # Replace the word 'ten' with the number '10'

df['study_hours_per_day'] = df['study_hours_per_day'].replace('ten', '10')
df['sleep_hours']         = df['sleep_hours'].replace('ten', '10')

In [81]:
# Convert to numeric (number) type

df['study_hours_per_day'] = pd.to_numeric(df['study_hours_per_day'], errors='coerce')
df['sleep_hours']         = pd.to_numeric(df['sleep_hours'],         errors='coerce')

### Value_count()

In [126]:
df['sleep_hours'].value_counts()

sleep_hours
10.000000    10
4.900000      3
3.000000      2
3.300000      2
5.500000      2
             ..
2.247229      1
5.185472      1
12.592937     1
5.437463      1
8.437898      1
Name: count, Length: 1023, dtype: int64

In [127]:
df2 = pd.read_csv("PSL Complete Dataset (2016-2025).csv")
df2.tail(2)
# df2["winner"].value_counts()

# df2["match_type"].unique()
df2[df2["match_type"] == "final"]["winner"].value_counts()["Islamabad United"]

np.int64(706)

In [128]:
print(df2.columns)
df2["bowling_team"].value_counts() + df2["batting_team"].value_counts()

Index(['id', 'match_id', 'date', 'season', 'venue', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder', 'winner', 'win_by',
       'match_type', 'player_of_match', 'umpire_1', 'umpire_2'],
      dtype='str')

bowling_team
Islamabad United     26312
Karachi Kings        24614
Lahore Qalandars     25099
Multan Sultans       20646
Peshawar Zalmi       26595
Quetta Gladiators    24302
Name: count, dtype: int64

### Sort()

In [195]:
df.sort_values("age", ascending= False, na_position= "first")

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
7,S1007,NaN,NaN,4.3,-0.912870,3.373847,Yes,76.041926,3.109453671639383,Fair,NaN,Bachelor,Average,4.307425,No,365.927950,2313
8,S1008,NaN,female,NaN,3.663144,6.903434,No,99.326218,4.4,Good,4.314662,NaN,Good,NaN,No,80.297148,5120
16,NaN,NaN,mle,1.0,5.010054,-1.429135,No,91.788047,3.726732301374966,Poor,7.471579,High School,NaN,NaN,Yes,57.869961,3090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,NaN,10.394181,NaN,10.0,4.794187,2.295641,No,76.777605,6.092561413821071,Fair,5.631324,High School,Poor,9.776491,Yes,80.191505,8892
413,S1413,10.267510,male,1.5,2.371914,1.590522,NaN,82.096003,0.4776832517411407,Poor,2.645505,NaN,Average,15.178722,No,65.845611,6115
1022,S1157,9.979164,mle,3.0,-0.741275,1.656586,No,98.268018,5.89871719001321,Poor,5.191340,Bachelor,Poor,2.600499,No,60.834797,2777
711,S1711,9.737673,M,3.2,1.666756,1.178224,NaN,102.530197,0.23826945338661876,Good,3.915227,High School,Average,8.572650,No,69.260645,4507
752,S1752,9.558960,M,4.5,2.573508,2.309560,Yes,71.879279,3.036875411888123,Good,1.670908,High School,Good,6.431041,Yes,71.010669,7873

In [130]:
movies = pd.read_csv("movies.csv")
movies.head(1)
movies.sort_values(["year_of_release", "title_x"], ascending= [True, False]).head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)

In [131]:
df.sort_index(axis=1).head(2)   #inplace = True

,EXAM_SCORE,EXERCISE_FREQUENCY,EXTRACURRICULAR_PARTICIPATION,GENDER,INTERNET_QUALITY,PARENTAL_EDUCATION_LEVEL,PART_TIME_JOB,RANDOM_ID,SLEEP_HOURS,SOCIAL_MEDIA_HOURS,STUDY_HOURS_PER_DAY,age,attendance_percentage,diet_quality,mental_health_rating,netflix_hours,student_id
0,59.197075,6.517918,Yes,femle,NaN,Master,No,9342,7.294122792755106,0.029056,0,21.048994,86.1535,Fair,11.789345,4.799806,S1000
1,98.718319,4.408856,No,FEMALE,Average,High School,No,5360,1.711612420026555,3.539930,NaN,NaN,NaN,Good,5.432582,3.400655,S1001

### Step 23 — Drop a Useless Column

The `random_id` column is just random numbers with no meaning. It has nothing to do with student performance. We remove it with `drop()`.

`columns=['random_id']` tells pandas we are dropping a column (not a row).

In [199]:
df.head(1)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,21.048994,femle,0.0,0.029056,4.799806,No,86.1535,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075

In [198]:
df.drop(columns=['random_id'], inplace = True)

In [200]:
# Remove the random_id column
df = df.drop(columns=['random_id'])

KeyError: "['random_id'] not found in axis"

In [146]:
# Verify — column is gone, shape should now be 16 columns
print(df.shape)
print(df.columns)

(1153, 16)
Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='str')

### Step 24 — Remove Duplicate Rows

`drop_duplicates()` removes rows that are exact copies of another row.  
`keep='first'` keeps the first occurrence and removes the rest.  
`reset_index(drop=True)` renumbers the rows cleanly after removal.

In [201]:
df.duplicated().sum()

np.int64(3)

In [202]:
df = df.drop_duplicates(keep='first')

In [92]:
# Remove duplicate rows

df = df.drop_duplicates(keep='first')
df = df.reset_index(drop=True)

In [203]:
# Verify — should be 0 now
df.duplicated().sum()

np.int64(0)

### Step 25 — Drop Rows with Missing Student ID

If a student has no ID, we cannot identify them. These rows are useless to us.

`dropna(subset=['student_id'])` drops only the rows where `student_id` is missing (NaN).

In [44]:
df.head(4)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,21.048994,femle,0.0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684
3,S1003,25.350557,F,10.0,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878

In [204]:
df.drop(index=[0,1])

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684
3,S1003,25.350557,F,10.0,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878
4,S1004,17.937754,FEMALE,10.0,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418
5,S1005,23.193687,male,7.2,0.762742,4.156124,No,82.212347,NaN,Fair,-1.725755,Master,Average,4.610438,No,106.436337
6,S1006,22.062970,femle,5.6,-0.033797,-3.916967,Yes,NaN,-4.759269743,Good,-3.266879,Master,Poor,2.176012,No,93.537529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0.0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582