In [50]:
import pandas as pd

print(pd.__version__)

3.0.6

In [51]:
marks = pd.Series([80, 90, 75, 88])

print(marks)

0    80
1    90
2    75
3    88
dtype: int64

In [52]:
marks = pd.Series(
    [80, 90, 75],
    index=["Ali", "Ahmed", "Sara"]
)

In [53]:
numbers = pd.Series([10, 20, 30])

print(numbers.iloc[0])  # 10
print(numbers.iloc[2])  # 30

10
30

In [54]:
marks = pd.Series([80, 90, 75, 88])

print(marks.sum())    # 333
print(marks.mean())   # 83.25
print(marks.max())    # 90
print(marks.min())    # 75
print(marks.count())  # 4

333
83.25
90
75
4

In [55]:
marks = pd.Series(
    [80, 90, 75, 88],
    index=["Ali", "Ahmed", "Sara", "Usman"]
)

print(marks[marks > 80])

Ahmed    90
Usman    88
dtype: int64

In [56]:
marks = pd.Series([80, None, 90, 75])

print(marks.isna())

0    False
1     True
2    False
3    False
dtype: bool

In [57]:
print(marks.isna().sum())  # 1

1

In [58]:
marks = marks.fillna(0)

print(marks)

0    80.0
1     0.0
2    90.0
3    75.0
dtype: float64

.index
Series ke tamam index labels deta hai.
s.index
# Index(["Ali", "Ahmed", "Sara", "Usman"], dtype="object")


.values
Series ki values deta hai, aam tor par NumPy array ki form mein.
s.values
# array([80, 90, 75, 88])


.dtype
Values ka data type batata hai.
s.dtype
# int64


.shape
Dimensions ka tuple deta hai.
s.shape
# (4,)


.size
Total elements ki tadaad batata hai.
s.size
# 4


.ndim
Dimensions ki tadaad batata hai. Series one-dimensional hoti hai.
s.ndim
# 1


.empty
Check karta hai ke Series empty hai ya nahi.
s.empty
# False


.name
Series ka naam return karta hai, agar set kiya gaya ho.
s.name
# None


.hasnans
Check karta hai ke Series mein missing values hain ya nahi.
s.hasnans
# False


.is_unique
Check karta hai ke tamam values unique hain ya nahi.
s.is_unique
# True

In [60]:
data = {
    "Name": ["Saad", "Ali", "Ahmed", "Sara", "Usman"],
    "Age": [25, 22, 24, 21, 23],
    "City": ["Islamabad", "Swat", "Peshawar", "Lahore", "Karachi"],
    "Marks": [90, 85, 78, 95, 82]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City  Marks
0   Saad   25  Islamabad     90
1    Ali   22       Swat     85
2  Ahmed   24   Peshawar     78
3   Sara   21     Lahore     95
4  Usman   23    Karachi     82

In [61]:
#access Data By Column
df["Name"]

0     Saad
1      Ali
2    Ahmed
3     Sara
4    Usman
Name: Name, dtype: str

In [12]:
df[["Name", "Age"]]

    Name  Age
0   Saad   25
1    Ali   22
2  Ahmed   24
3   Sara   21
4  Usman   23

In [62]:
df1 = pd.read_csv("Messy_student_data.csv")

# Complete data print karna
df = df1.copy()
df

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [63]:
df.head()
df.head(10)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
5,S1005,23.193687,male,7.2,0.762742,4.156124,No,82.212347,NaN,Fair,-1.725755,Master,Average,4.610438,No,106.436337,1863
6,S1006,22.062970,femle,5.6,-0.033797,-3.916967,Yes,NaN,-4.759269743,Good,-3.266879,Master,Poor,2.176012,No,93.537529,4953
7,S1007,NaN,NaN,4.3,-0.912870,3.373847,Yes,76.041926,3.109453671639383,Fair,NaN,Bachelor,Average,4.307425,No,365.927950,2313
8,S1008,NaN,female,NaN,3.663144,6.903434,No,99.326218,4.4,Good,4.314662,NaN,Good,NaN,No,80.297148,5120
9,S1009,23.669075,FEMALE,4.8,5.199887,-0.088103,No,96.742474,7.054294851537139,Good,2.072327,Bachelor,NaN,11.481817,Yes,100.123883,2126

In [64]:
df.tail()
df.tail(10)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
1143,S1338,24.380113,femle,5,3.481359,1.715062,Yes,79.208616,6.727704165795762,Good,-1.265984,Bachelor,Average,1.868575,Yes,NaN,7959
1144,S1907,15.364776,F,3.3,2.181984,0.316475,No,62.172960,3.2380552425191933,NaN,10.433580,High School,Average,1.511964,No,56.787399,4046
1145,S1530,15.523021,M,NaN,-4.706727,2.879551,No,NaN,2.3548074279028546,Good,2.329910,Master,Good,3.383579,Yes,81.632289,9867
1146,S1455,19.711286,MALE,8.3,6.992849,0.264495,Yes,87.034990,7.157521426517684,Fair,6.943018,High School,Average,12.083630,No,102.496252,2370
1147,S1647,20.430457,femle,ten,4.165038,NaN,NaN,83.729647,11.225482415792479,NaN,3.424837,NaN,Average,-2.224919,No,83.828071,1643
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [65]:
#it Gives Random 1 row and if pass number of Row then Return that number of Rows
df.sample()
df.sample(5)

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
1136,S1031,17.297855,Other,1.5,8.563020,4.859585,Yes,99.382320,14.242114036652877,Fair,5.293917,Bachelor,Average,4.240202,Yes,52.151921,9178
1090,S1397,NaN,femle,2.3,3.824875,3.339298,Yes,97.538733,10.04643160496616,Fair,4.306976,Bachelor,Good,16.708234,Yes,70.824708,5975
611,S1611,20.670259,mle,6,-1.347579,-2.845327,No,NaN,-2.745708287,unknown,8.784937,High School,Poor,4.368668,No,95.043510,7235
64,S1064,24.345760,male,ten,NaN,5.232788,No,83.981487,4.12561881700743,Good,6.309736,High School,Poor,6.052132,Yes,NaN,8928
1037,S1202,16.127600,mle,3.7,-0.582876,NaN,No,81.090661,6.707362920187979,Fair,NaN,NaN,Average,8.852229,No,NaN,4876

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1153 entries, 0 to 1152
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1032 non-null   str
 1   age                            1041 non-null   float64
 2   GENDER                         1039 non-null   str
 3   STUDY_HOURS_PER_DAY            998 non-null    str
 4   SOCIAL_MEDIA_HOURS             1044 non-null   float64
 5   netflix_hours                  1032 non-null   float64
 6   PART_TIME_JOB                  1032 non-null   str
 7   attendance_percentage          1039 non-null   float64
 8   SLEEP_HOURS                    1044 non-null   str
 9   diet_quality                   1047 non-null   str
 10  EXERCISE_FREQUENCY             1042 non-null   float64
 11  PARENTAL_EDUCATION_LEVEL       947 non-null    str
 12  INTERNET_QUALITY               1043 non-null   str
 13  mental_health_rating           1041 non-null   float64
 14  EXTRACURRICULAR_PARTICIPATION  1039 non-null   str
 15  EXAM_SCORE                     1039 non-null   float64
 16  RANDOM_ID                      1153 non-null   int64
dtypes: float64(7), int64(1), str(9)
memory usage: 153.3 KB

In [67]:

df.isnull()

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1149,True,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,False
1150,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1151,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1152,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False

In [68]:
df.isnull().sum()

student_id                       121
age                              112
GENDER                           114
STUDY_HOURS_PER_DAY              155
SOCIAL_MEDIA_HOURS               109
netflix_hours                    121
PART_TIME_JOB                    121
attendance_percentage            114
SLEEP_HOURS                      109
diet_quality                     106
EXERCISE_FREQUENCY               111
PARENTAL_EDUCATION_LEVEL         206
INTERNET_QUALITY                 110
mental_health_rating             112
EXTRACURRICULAR_PARTICIPATION    114
EXAM_SCORE                       114
RANDOM_ID                          0
dtype: int64

In [69]:
df.isna()

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1149,True,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,False
1150,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1151,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1152,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False

In [70]:
df.isna().sum()

student_id                       121
age                              112
GENDER                           114
STUDY_HOURS_PER_DAY              155
SOCIAL_MEDIA_HOURS               109
netflix_hours                    121
PART_TIME_JOB                    121
attendance_percentage            114
SLEEP_HOURS                      109
diet_quality                     106
EXERCISE_FREQUENCY               111
PARENTAL_EDUCATION_LEVEL         206
INTERNET_QUALITY                 110
mental_health_rating             112
EXTRACURRICULAR_PARTICIPATION    114
EXAM_SCORE                       114
RANDOM_ID                          0
dtype: int64

In [72]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1148    False
1149    False
1150    False
1151    False
1152    False
Length: 1153, dtype: bool

In [73]:
df.duplicated().sum()

np.int64(3)

In [74]:
df[df.duplicated(keep=False)]

,student_id,age,GENDER,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
873,S1873,17.648301,F,4.3,NaN,-3.233988,No,82.252457,-0.489389156,Fair,7.483958,High School,Good,10.956222,No,84.367479,8136
874,S1874,16.940867,M,5.1,2.731454,0.307086,No,95.648970,8.048016356998517,unknown,2.259864,Master,Average,9.087426,No,96.000869,9779
875,S1875,20.513999,femle,7.6,2.040626,NaN,NaN,93.904316,6.40760898746424,Poor,-0.507753,High School,Good,7.078776,NaN,98.565704,7398
876,S1873,17.648301,F,4.3,NaN,-3.233988,No,82.252457,-0.489389156,Fair,7.483958,High School,Good,10.956222,No,84.367479,8136
877,S1874,16.940867,M,5.1,2.731454,0.307086,No,95.648970,8.048016356998517,unknown,2.259864,Master,Average,9.087426,No,96.000869,9779
878,S1875,20.513999,femle,7.6,2.040626,NaN,NaN,93.904316,6.40760898746424,Poor,-0.507753,High School,Good,7.078776,NaN,98.565704,7398

In [75]:
df.rename(columns={"GENDER": "gender"})

,student_id,age,gender,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [26]:
df.rename(columns={"GENDER": "gender"}, inplace=True)
df

,student_id,age,gender,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [27]:
df["gender"].value_counts()

gender
MALE        103
 F           99
mle          91
female       89
 M           81
male         79
femle        69
FEMALE       67
 female      53
 male        46
 femle       43
  F          39
 mle         36
 FEMALE      35
 MALE        35
Other        34
  M          30
 Other       10
Name: count, dtype: int64

In [28]:
df["gender"].value_counts(dropna=False)

gender
NaN         114
MALE        103
 F           99
mle          91
female       89
 M           81
male         79
femle        69
FEMALE       67
 female      53
 male        46
 femle       43
  F          39
 mle         36
 FEMALE      35
 MALE        35
Other        34
  M          30
 Other       10
Name: count, dtype: int64

In [29]:
data = {
    "Name": ["Saad", "Ali", "Ahmed", "Sara", "Usman"],
    "Age": [25, 22, 24, 21, 23],
    "City": ["Islamabad", "Swat", "Peshawar", "Lahore", "Karachi"],
    "Marks": [90, 85, 78, 95, 82]
}

student = pd.DataFrame(data)

print(student)

    Name  Age       City  Marks
0   Saad   25  Islamabad     90
1    Ali   22       Swat     85
2  Ahmed   24   Peshawar     78
3   Sara   21     Lahore     95
4  Usman   23    Karachi     82

In [30]:
student.iloc[0]

Name          Saad
Age             25
City     Islamabad
Marks           90
Name: 0, dtype: object

In [31]:
student.iloc[0:3, 0:2]

    Name  Age
0   Saad   25
1    Ali   22
2  Ahmed   24

In [32]:

data = {
    "Name": ["Saad", "Ali", "Ahmed", "Sara", "Usman"],
    "Age": [25, 22, 24, 21, 23],
    "City": ["Islamabad", "Swat", "Peshawar", "Lahore", "Karachi"],
    "Marks": [90, 85, 78, 95, 82]
}

students = pd.DataFrame(data)

students = students.set_index('Name')
students

       Age       City  Marks
Name
Saad    25  Islamabad     90
Ali     22       Swat     85
Ahmed   24   Peshawar     78
Sara    21     Lahore     95
Usman   23    Karachi     82

In [33]:
students.loc[["Saad", "Ali"]]

      Age       City  Marks
Name
Saad   25  Islamabad     90
Ali    22       Swat     85

In [34]:
students.loc["Saad":"Sara", "Age":"City"]

       Age       City
Name
Saad    25  Islamabad
Ali     22       Swat
Ahmed   24   Peshawar
Sara    21     Lahore

In [35]:
df

,student_id,age,gender,STUDY_HOURS_PER_DAY,SOCIAL_MEDIA_HOURS,netflix_hours,PART_TIME_JOB,attendance_percentage,SLEEP_HOURS,diet_quality,EXERCISE_FREQUENCY,PARENTAL_EDUCATION_LEVEL,INTERNET_QUALITY,mental_health_rating,EXTRACURRICULAR_PARTICIPATION,EXAM_SCORE,RANDOM_ID
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [36]:
df.columns

Index(['student_id ', 'age ', 'gender', 'STUDY_HOURS_PER_DAY',
       'SOCIAL_MEDIA_HOURS', 'netflix_hours ', 'PART_TIME_JOB',
       'attendance_percentage ', 'SLEEP_HOURS', 'diet_quality ',
       'EXERCISE_FREQUENCY', 'PARENTAL_EDUCATION_LEVEL', 'INTERNET_QUALITY',
       'mental_health_rating ', 'EXTRACURRICULAR_PARTICIPATION', 'EXAM_SCORE',
       'RANDOM_ID'],
      dtype='str')

In [37]:
df.columns.str.strip()

Index(['student_id', 'age', 'gender', 'STUDY_HOURS_PER_DAY',
       'SOCIAL_MEDIA_HOURS', 'netflix_hours', 'PART_TIME_JOB',
       'attendance_percentage', 'SLEEP_HOURS', 'diet_quality',
       'EXERCISE_FREQUENCY', 'PARENTAL_EDUCATION_LEVEL', 'INTERNET_QUALITY',
       'mental_health_rating', 'EXTRACURRICULAR_PARTICIPATION', 'EXAM_SCORE',
       'RANDOM_ID'],
      dtype='str')

In [79]:

df.columns = df.columns.str.strip().str.lower()

In [80]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score',
       'random_id'],
      dtype='str')

In [81]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,ten,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,ten,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714

In [82]:
df["study_hours_per_day"]

0         0
1       NaN
2       NaN
3       ten
4       ten
       ...
1148      0
1149    NaN
1150    3.8
1151    1.3
1152    4.1
Name: study_hours_per_day, Length: 1153, dtype: str

In [42]:
df["study_hours_per_day"].replace("ten", "10")

0         0
1       NaN
2       NaN
3        10
4        10
       ...
1148      0
1149    NaN
1150    3.8
1151    1.3
1152    4.1
Name: study_hours_per_day, Length: 1153, dtype: str

In [83]:
df["study_hours_per_day"] = df["study_hours_per_day"].replace("ten", "10")
df["study_hours_per_day"].astype(int)

ValueError: cannot convert float NaN to integer

In [76]:
df["study_hours_per_day"] = pd.to_numeric(df["study_hours_per_day"], errors= "coerce")
df["study_hours_per_day"]

KeyError: 'study_hours_per_day'

In [84]:
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,10,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,10,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [85]:
df["sleep_hours"]

0        7.294122792755106
1        1.711612420026555
2       0.2453070425737236
3        4.632657480507504
4       5.4664425896840125
               ...
1148    2.2472285912248626
1149     5.185471755983927
1150    12.592937372956582
1151    5.4374633631424105
1152      8.43789753066304
Name: sleep_hours, Length: 1153, dtype: str

In [ ]:
df["sleep_hours"] = df["sleep_hours"].replace("ten", "10")
df["sleep_hours"] = pd.to_numeric(df["sleep_hours"], errors= "coerce")

In [86]:
df["sleep_hours"]

0        7.294122792755106
1        1.711612420026555
2       0.2453070425737236
3        4.632657480507504
4       5.4664425896840125
               ...
1148    2.2472285912248626
1149     5.185471755983927
1150    12.592937372956582
1151    5.4374633631424105
1152      8.43789753066304
Name: sleep_hours, Length: 1153, dtype: str

In [87]:
df.sort_values('age')

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
752,S1752,9.558960,M,4.5,2.573508,2.309560,Yes,71.879279,3.036875411888123,Good,1.670908,High School,Good,6.431041,Yes,71.010669,7873
711,S1711,9.737673,M,3.2,1.666756,1.178224,NaN,102.530197,0.23826945338661876,Good,3.915227,High School,Average,8.572650,No,69.260645,4507
1022,S1157,9.979164,mle,3,-0.741275,1.656586,No,98.268018,5.89871719001321,Poor,5.191340,Bachelor,Poor,2.600499,No,60.834797,2777
413,S1413,10.267510,male,1.5,2.371914,1.590522,NaN,82.096003,0.4776832517411407,Poor,2.645505,NaN,Average,15.178722,No,65.845611,6115
344,NaN,10.394181,NaN,10,4.794187,2.295641,No,76.777605,6.092561413821071,Fair,5.631324,High School,Poor,9.776491,Yes,80.191505,8892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,S1693,NaN,femle,4.9,NaN,0.362847,No,86.493572,11.742257646629916,Fair,3.859196,High School,Average,8.389858,No,92.283417,6728
1088,S1163,NaN,MALE,NaN,6.107235,-0.242104,No,88.809034,3.622636981086323,Poor,2.059178,Master,Good,4.214774,No,63.933691,5647
1090,S1397,NaN,femle,2.3,3.824875,3.339298,Yes,97.538733,10.04643160496616,Fair,4.306976,Bachelor,Good,16.708234,Yes,70.824708,5975
1124,S1434,NaN,male,0,1.905355,-1.785556,No,72.677913,5.5355793344173145,Fair,4.901445,High School,Good,5.327576,No,22.791578,5947
1128,S1804,NaN,NaN,4.3,2.886653,2.554458,Yes,85.316150,-6.111738879,Good,-0.689394,High School,Average,-2.983370,Yes,58.451980,2574

In [88]:
df.sort_values('age', ascending=False)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
112,S1112,31.463841,F,4.474972426161429,1.490353,1.928172,No,93.471017,NaN,Fair,2.546406,Bachelor,Poor,NaN,Yes,44.003704,5763
1028,NaN,30.656267,NaN,NaN,1.656650,3.629570,Yes,89.447216,9.078935161168328,unknown,2.979960,NaN,Good,5.021615,No,37.103170,7771
523,S1523,30.536230,Other,NaN,2.431178,1.435922,No,83.999579,8.548053253540145,Good,5.742807,High School,Average,3.766568,No,64.787444,4475
791,S1791,30.138522,MALE,5.918670304382115,0.733097,-0.600908,No,79.421132,ten,Fair,-2.922422,Bachelor,Good,6.661633,No,97.908987,6753
113,S1113,29.959898,M,3,0.593798,-0.592660,No,83.189577,0.7741183546165109,Fair,3.320722,Bachelor,Average,5.214553,No,53.620324,7734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,S1693,NaN,femle,4.9,NaN,0.362847,No,86.493572,11.742257646629916,Fair,3.859196,High School,Average,8.389858,No,92.283417,6728
1088,S1163,NaN,MALE,NaN,6.107235,-0.242104,No,88.809034,3.622636981086323,Poor,2.059178,Master,Good,4.214774,No,63.933691,5647
1090,S1397,NaN,femle,2.3,3.824875,3.339298,Yes,97.538733,10.04643160496616,Fair,4.306976,Bachelor,Good,16.708234,Yes,70.824708,5975
1124,S1434,NaN,male,0,1.905355,-1.785556,No,72.677913,5.5355793344173145,Fair,4.901445,High School,Good,5.327576,No,22.791578,5947
1128,S1804,NaN,NaN,4.3,2.886653,2.554458,Yes,85.316150,-6.111738879,Good,-0.689394,High School,Average,-2.983370,Yes,58.451980,2574

In [89]:
df.sort_values('age', ascending=False, na_position='last')

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
112,S1112,31.463841,F,4.474972426161429,1.490353,1.928172,No,93.471017,NaN,Fair,2.546406,Bachelor,Poor,NaN,Yes,44.003704,5763
1028,NaN,30.656267,NaN,NaN,1.656650,3.629570,Yes,89.447216,9.078935161168328,unknown,2.979960,NaN,Good,5.021615,No,37.103170,7771
523,S1523,30.536230,Other,NaN,2.431178,1.435922,No,83.999579,8.548053253540145,Good,5.742807,High School,Average,3.766568,No,64.787444,4475
791,S1791,30.138522,MALE,5.918670304382115,0.733097,-0.600908,No,79.421132,ten,Fair,-2.922422,Bachelor,Good,6.661633,No,97.908987,6753
113,S1113,29.959898,M,3,0.593798,-0.592660,No,83.189577,0.7741183546165109,Fair,3.320722,Bachelor,Average,5.214553,No,53.620324,7734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,S1693,NaN,femle,4.9,NaN,0.362847,No,86.493572,11.742257646629916,Fair,3.859196,High School,Average,8.389858,No,92.283417,6728
1088,S1163,NaN,MALE,NaN,6.107235,-0.242104,No,88.809034,3.622636981086323,Poor,2.059178,Master,Good,4.214774,No,63.933691,5647
1090,S1397,NaN,femle,2.3,3.824875,3.339298,Yes,97.538733,10.04643160496616,Fair,4.306976,Bachelor,Good,16.708234,Yes,70.824708,5975
1124,S1434,NaN,male,0,1.905355,-1.785556,No,72.677913,5.5355793344173145,Fair,4.901445,High School,Good,5.327576,No,22.791578,5947
1128,S1804,NaN,NaN,4.3,2.886653,2.554458,Yes,85.316150,-6.111738879,Good,-0.689394,High School,Average,-2.983370,Yes,58.451980,2574

In [90]:
df.sort_values('age', ascending=False, na_position='first')

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
7,S1007,NaN,NaN,4.3,-0.912870,3.373847,Yes,76.041926,3.109453671639383,Fair,NaN,Bachelor,Average,4.307425,No,365.927950,2313
8,S1008,NaN,female,NaN,3.663144,6.903434,No,99.326218,4.4,Good,4.314662,NaN,Good,NaN,No,80.297148,5120
16,NaN,NaN,mle,1,5.010054,-1.429135,No,91.788047,3.726732301374966,Poor,7.471579,High School,NaN,NaN,Yes,57.869961,3090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,NaN,10.394181,NaN,10,4.794187,2.295641,No,76.777605,6.092561413821071,Fair,5.631324,High School,Poor,9.776491,Yes,80.191505,8892
413,S1413,10.267510,male,1.5,2.371914,1.590522,NaN,82.096003,0.4776832517411407,Poor,2.645505,NaN,Average,15.178722,No,65.845611,6115
1022,S1157,9.979164,mle,3,-0.741275,1.656586,No,98.268018,5.89871719001321,Poor,5.191340,Bachelor,Poor,2.600499,No,60.834797,2777
711,S1711,9.737673,M,3.2,1.666756,1.178224,NaN,102.530197,0.23826945338661876,Good,3.915227,High School,Average,8.572650,No,69.260645,4507
752,S1752,9.558960,M,4.5,2.573508,2.309560,Yes,71.879279,3.036875411888123,Good,1.670908,High School,Good,6.431041,Yes,71.010669,7873

In [91]:
df.head(1)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.1535,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342

In [92]:
df.drop(columns=["random_id"])

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684
3,S1003,25.350557,F,10,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878
4,S1004,17.937754,FEMALE,10,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582

In [93]:
df.head(1)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.1535,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342

In [94]:
df.drop(columns=["random_id"], inplace = True) #inplace is using to store changes in your data like now random_id df se remove ho jaye ga.

In [95]:
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684
3,S1003,25.350557,F,10,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878
4,S1004,17.937754,FEMALE,10,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582

In [96]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Saad", "Ali", np.nan, "Sara", "Usman"],
    "Age": [25, 22, 24, 21, np.nan],
    "City": ["Islamabad", "Swat", "Peshawar", np.nan, "Karachi"],
    "Marks": [90, 85, 30, 95, 82]
}

student = pd.DataFrame(data)

print(student)

    Name   Age       City  Marks
0   Saad  25.0  Islamabad     90
1    Ali  22.0       Swat     85
2    NaN  24.0   Peshawar     30
3   Sara  21.0        NaN     95
4  Usman   NaN    Karachi     82

In [97]:
student = student.dropna(axis=0)
student

   Name   Age       City  Marks
0  Saad  25.0  Islamabad     90
1   Ali  22.0       Swat     85

In [98]:
student = student.dropna(axis=0)
student

   Name   Age       City  Marks
0  Saad  25.0  Islamabad     90
1   Ali  22.0       Swat     85

In [44]:
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,NaN,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,NaN,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,10,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,10,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091,8669
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354,5427
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270,8290
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948,2093
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582,8403

In [99]:
df['age'] = df['age'].fillna(df['age'].median())
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075
1,S1001,20.496321,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319
2,S1002,20.496321,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684
3,S1003,25.350557,F,10,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878
4,S1004,17.937754,FEMALE,10,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,S1431,20.169749,F,0,0.147439,2.220364,No,82.281313,2.2472285912248626,Poor,4.636831,NaN,Average,2.064658,No,31.321091
1149,NaN,22.671669,femle,NaN,1.463998,NaN,No,98.556989,5.185471755983927,Fair,NaN,Master,Good,-0.420232,No,45.230354
1150,S1492,16.382979,MALE,3.8,-0.733763,-1.671703,No,79.850885,12.592937372956582,Good,0.875599,NaN,Good,4.719068,No,70.239270
1151,S1979,20.676107,MALE,1.3,1.741795,-0.334418,No,76.300402,5.4374633631424105,Good,6.343053,High School,Poor,4.319858,No,55.382948
1152,S1902,24.716932,male,4.1,1.071961,4.197893,No,71.468550,8.43789753066304,unknown,0.827871,Master,NaN,NaN,No,67.190582

In [47]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score,random_id
0,S1000,21.048994,femle,0,0.029056,4.799806,No,86.153500,7.294122792755106,Fair,6.517918,Master,NaN,11.789345,Yes,59.197075,9342
1,S1001,20.496321,FEMALE,NaN,3.539930,3.400655,No,NaN,1.711612420026555,Good,4.408856,High School,Average,5.432582,No,98.718319,5360
2,S1002,20.496321,MALE,NaN,10.270434,1.780307,No,92.813065,0.2453070425737236,Poor,-0.477552,NaN,Poor,-3.244017,No,33.361684,9117
3,S1003,25.350557,F,10,0.816828,5.861446,No,70.689033,4.632657480507504,Poor,0.581851,Master,Good,5.000688,Yes,27.830878,2436
4,S1004,17.937754,FEMALE,10,5.320886,-0.077509,No,NaN,5.4664425896840125,Fair,5.148622,Master,NaN,2.408725,No,60.686418,7714

In [113]:
df.drop(columns=["random_id"], inplace=True, errors="ignore")

In [121]:
df['gender'].fillna("unknown")
df['gender'] = df['gender'].str.strip().str.lower()
df['gender']

0       unknown
1       unknown
2       unknown
3       unknown
4       unknown
         ...
1148    unknown
1149    unknown
1150    unknown
1151    unknown
1152    unknown
Name: gender, Length: 1153, dtype: str

In [111]:
gender_map = {
    'female' : "Female",
    'femle' : "Female",
    'f' : "Female",
    'male' : "Male",
    'mle' : "Male",
    'm' : "Male",
    'other' : "Other",
    'unknow' : "Unkown",
}
df['gender'] = df['gender'].map(gender_map)
df['gender']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1148    NaN
1149    NaN
1150    NaN
1151    NaN
1152    NaN
Name: gender, Length: 1153, dtype: str

In [109]:
df.isnull().sum()

student_id                        121
age                                 0
gender                           1153
study_hours_per_day               155
social_media_hours                109
netflix_hours                     121
part_time_job                     121
attendance_percentage             114
sleep_hours                       109
diet_quality                      106
exercise_frequency                111
parental_education_level          206
internet_quality                  110
mental_health_rating              112
extracurricular_participation     114
exam_score                        114
dtype: int64

In [114]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='str')

In [115]:
df["student_id"].isnull().sum()

np.int64(121)

In [119]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")

df["age"] = df["age"].fillna(df["age"].median())
df['age']
df["age"].isnull().sum()

np.int64(0)

In [122]:
df["gender"].value_counts(dropna=False)

gender
unknown    1153
Name: count, dtype: int64

In [123]:
df["gender"] = df["gender"].fillna(df["gender"].mode()[0])

In [124]:
df["gender"] = df["gender"].map({
    "Male": 0,
    "Female": 1,
    "Other": 2
})

In [125]:
df["study_hours_per_day"] = pd.to_numeric(
    df["study_hours_per_day"], errors="coerce"
)

df["study_hours_per_day"] = df["study_hours_per_day"].fillna(
    df["study_hours_per_day"].mean()
)

In [126]:
df["social_media_hours"] = pd.to_numeric(
    df["social_media_hours"], errors="coerce"
)

df["social_media_hours"] = df["social_media_hours"].fillna(
    df["social_media_hours"].median()
)

In [127]:
df["netflix_hours"] = pd.to_numeric(
    df["netflix_hours"], errors="coerce"
)

df["netflix_hours"] = df["netflix_hours"].fillna(
    df["netflix_hours"].mean()
)

In [128]:
df["part_time_job"].value_counts(dropna=False)

part_time_job
No       590
 No      219
Yes      156
NaN      121
 Yes      67
Name: count, dtype: int64

In [129]:
df["part_time_job"] = df["part_time_job"].fillna(
    df["part_time_job"].mode()[0]
)

In [130]:
df["part_time_job"] = df["part_time_job"].map({
    "Yes": 1,
    "No": 0
})

In [131]:
df["attendance_percentage"] = pd.to_numeric(
    df["attendance_percentage"], errors="coerce"
)

df["attendance_percentage"] = df["attendance_percentage"].fillna(
    df["attendance_percentage"].mean()
)

In [132]:
df["sleep_hours"] = pd.to_numeric(
    df["sleep_hours"], errors="coerce"
)

df["sleep_hours"] = df["sleep_hours"].fillna(
    df["sleep_hours"].median()
)

In [133]:
df["diet_quality"].value_counts(dropna=False)

diet_quality
Fair       266
Good       245
 Fair      138
Poor       121
unknown    116
 Good      109
NaN        106
 Poor       52
Name: count, dtype: int64

In [134]:
df["diet_quality"] = df["diet_quality"].fillna(
    df["diet_quality"].mode()[0]
)

In [135]:
df["diet_quality"] = df["diet_quality"].map({
    "Poor": 0,
    "Fair": 1,
    "Good": 2
})

In [136]:
df["exercise_frequency"] = pd.to_numeric(
    df["exercise_frequency"], errors="coerce"
)

df["exercise_frequency"] = df["exercise_frequency"].fillna(
    df["exercise_frequency"].median()
)

In [137]:
df["parental_education_level"].value_counts(dropna=False)

parental_education_level
High School      289
Bachelor         268
NaN              206
Master           129
 High School     116
 Bachelor         91
 Master           54
Name: count, dtype: int64

In [138]:
df["parental_education_level"] = (
    df["parental_education_level"].fillna(
        df["parental_education_level"].mode()[0]
    )
)

In [139]:
df["parental_education_level"] = df[
    "parental_education_level"
].map({
    "High School": 0,
    "Bachelor": 1,
    "Master": 2,
    "Doctorate": 3
})

In [140]:
df["internet_quality"].value_counts(dropna=False)

internet_quality
Good         316
Average      287
 Good        160
Poor         117
 Average     112
NaN          110
 Poor         51
Name: count, dtype: int64

In [141]:
df["internet_quality"] = df["internet_quality"].fillna(
    df["internet_quality"].mode()[0]
)

In [142]:
df["internet_quality"] = df["internet_quality"].map({
    "Poor": 0,
    "Average": 1,
    "Good": 2
})

In [143]:
df["mental_health_rating"] = pd.to_numeric(
    df["mental_health_rating"], errors="coerce"
)

df["mental_health_rating"] = df["mental_health_rating"].fillna(
    df["mental_health_rating"].median()
)

In [144]:
df["extracurricular_participation"].value_counts(dropna=False)

extracurricular_participation
No       494
Yes      244
 No      212
NaN      114
 Yes      89
Name: count, dtype: int64

In [145]:
df["extracurricular_participation"] = (
    df["extracurricular_participation"].fillna(
        df["extracurricular_participation"].mode()[0]
    )
)

In [146]:
df["extracurricular_participation"] = (
    df["extracurricular_participation"].map({
        "Yes": 1,
        "No": 0
    })
)

In [147]:
df["exam_score"] = pd.to_numeric(
    df["exam_score"], errors="coerce"
)

df["exam_score"] = df["exam_score"].fillna(
    df["exam_score"].mean()
)

In [148]:
df.isnull().sum()

student_id                        121
age                                 0
gender                           1153
study_hours_per_day                 0
social_media_hours                  0
netflix_hours                       0
part_time_job                     286
attendance_percentage               0
sleep_hours                         0
diet_quality                      415
exercise_frequency                  0
parental_education_level          261
internet_quality                  323
mental_health_rating                0
extracurricular_participation     301
exam_score                          0
dtype: int64

In [149]:
df.duplicated().sum()

np.int64(3)

In [151]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='str')

In [ ]:
df['netflix_hours'] = df['netflix_hours'].clip(lower=0)
df['social_media_hours'] = df['social_media_hours'].clip(lower=0)
df['netflix_hours'] = df['netflix_hours'].clip(lower=0)
df['netflix_hours'] = df['netflix_hours'].clip(lower=0)

In [155]:
(df['exam_score']> 100).sum()

np.int64(0)

In [ ]:

df['exam_score'] = df['exam_score'].clip(lower=0, upper=(100))
df['exam_score']

0       59.197075
1       98.718319
2       33.361684
3       27.830878
4       60.686418
          ...
1148    31.321091
1149    45.230354
1150    70.239270
1151    55.382948
1152    67.190582
Name: exam_score, Length: 1153, dtype: float64

In [156]:
df['exam_score'].max()

np.float64(100.0)

In [157]:
df.to_csv("student_data_clean.csv", index=False)

In [158]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='str')

In [160]:
[df['exam_score'] > 80]

[0       False
 1        True
 2       False
 3       False
 4       False
         ...
 1148    False
 1149    False
 1150    False
 1151    False
 1152    False
 Name: exam_score, Length: 1153, dtype: bool]

In [164]:
df[(df['exam_score'] > 80) & (df['study_hours_per_day'] > 5)]

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
1,S1001,20.496321,NaN,5.06586,3.539930,3.400655,0.0,83.906115,1.711612,2.0,4.408856,NaN,1.0,5.432582,NaN,98.718319
5,S1005,23.193687,NaN,7.20000,0.762742,4.156124,0.0,82.212347,6.054516,1.0,-1.725755,2.0,NaN,4.610438,0.0,100.000000
6,S1006,22.062970,NaN,5.60000,-0.033797,0.000000,1.0,83.906115,-4.759270,NaN,-3.266879,2.0,0.0,2.176012,0.0,93.537529
8,S1008,20.496321,NaN,5.06586,3.663144,6.903434,0.0,99.326218,4.400000,2.0,4.314662,0.0,2.0,5.390964,0.0,80.297148
21,S1021,17.764852,NaN,5.06586,3.073096,2.011406,0.0,98.566813,6.054516,NaN,3.315721,0.0,2.0,6.722182,0.0,83.384401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,S1021,19.800509,NaN,5.06586,-0.330220,2.011406,0.0,91.451755,6.054516,NaN,-2.753594,NaN,NaN,7.271243,NaN,82.513033
1142,S1740,27.535727,NaN,10.00000,3.390119,1.002322,0.0,83.785793,4.883522,0.0,8.260844,0.0,NaN,2.273386,NaN,83.807246
1145,S1530,15.523021,NaN,5.06586,-4.706727,2.879551,NaN,83.906115,2.354807,2.0,2.329910,NaN,2.0,3.383579,1.0,81.632289
1146,S1455,19.711286,NaN,8.30000,6.992849,0.264495,1.0,87.034990,7.157521,1.0,6.943018,NaN,NaN,12.083630,0.0,100.000000
1147,S1647,20.430457,NaN,10.00000,4.165038,2.011406,0.0,83.729647,11.225482,1.0,3.424837,0.0,1.0,-2.224919,0.0,83.828071

In [ ]:
df["student_id"].isnull().sum()

np.int64(121)

In [165]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Saad", "Ali", np.nan, "Sara", "Usman"],
    "Age": [25, 22, 24, 21, np.nan],
    "City": ["Islamabad", "Swat", "Peshawar", np.nan, "Karachi"],
    "Marks": [90, 85, 30, 95, 82]
}

s = pd.DataFrame(data)

print(s)

    Name   Age       City  Marks
0   Saad  25.0  Islamabad     90
1    Ali  22.0       Swat     85
2    NaN  24.0   Peshawar     30
3   Sara  21.0        NaN     95
4  Usman   NaN    Karachi     82

In [166]:
s[s['Age'].isin([22,21,24])]

   Name   Age      City  Marks
1   Ali  22.0      Swat     85
2   NaN  24.0  Peshawar     30
3  Sara  21.0       NaN     95

In [167]:
s[~s['Age'].isin([22,21,24])]

    Name   Age       City  Marks
0   Saad  25.0  Islamabad     90
4  Usman   NaN    Karachi     82

In [168]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='str')

In [171]:
df['internet_quality']

0       2.0
1       1.0
2       NaN
3       2.0
4       2.0
       ...
1148    1.0
1149    2.0
1150    2.0
1151    NaN
1152    2.0
Name: internet_quality, Length: 1153, dtype: float64

In [172]:
df[df['internet_quality'].isin([1]) | df['internet_quality'].isin([2])]

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,21.048994,NaN,0.00000,0.029056,4.799806,0.0,86.153500,7.294123,1.0,6.517918,NaN,2.0,11.789345,1.0,59.197075
1,S1001,20.496321,NaN,5.06586,3.539930,3.400655,0.0,83.906115,1.711612,2.0,4.408856,NaN,1.0,5.432582,NaN,98.718319
3,S1003,25.350557,NaN,10.00000,0.816828,5.861446,NaN,70.689033,4.632657,NaN,0.581851,NaN,2.0,5.000688,1.0,27.830878
4,S1004,17.937754,NaN,10.00000,5.320886,0.000000,0.0,83.906115,5.466443,1.0,5.148622,2.0,2.0,2.408725,0.0,60.686418
8,S1008,20.496321,NaN,5.06586,3.663144,6.903434,0.0,99.326218,4.400000,2.0,4.314662,0.0,2.0,5.390964,0.0,80.297148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,S1647,20.430457,NaN,10.00000,4.165038,2.011406,0.0,83.729647,11.225482,1.0,3.424837,0.0,1.0,-2.224919,0.0,83.828071
1148,S1431,20.169749,NaN,0.00000,0.147439,2.220364,NaN,82.281313,2.247229,NaN,4.636831,0.0,1.0,2.064658,NaN,31.321091
1149,NaN,22.671669,NaN,5.06586,1.463998,2.011406,NaN,98.556989,5.185472,1.0,3.046520,NaN,2.0,-0.420232,0.0,45.230354
1150,S1492,16.382979,NaN,3.80000,-0.733763,0.000000,NaN,79.850885,12.592937,2.0,0.875599,0.0,2.0,4.719068,0.0,70.239270
1152,S1902,24.716932,NaN,4.10000,1.071961,4.197893,NaN,71.468550,8.437898,NaN,0.827871,2.0,2.0,5.390964,NaN,67.190582

In [173]:
s

    Name   Age       City  Marks
0   Saad  25.0  Islamabad     90
1    Ali  22.0       Swat     85
2    NaN  24.0   Peshawar     30
3   Sara  21.0        NaN     95
4  Usman   NaN    Karachi     82

In [174]:
s['Age_Marks'] = s['Age'] = s['Marks']

In [175]:
s

    Name  Age       City  Marks  Age_Marks
0   Saad   90  Islamabad     90         90
1    Ali   85       Swat     85         85
2    NaN   30   Peshawar     30         30
3   Sara   95        NaN     95         95
4  Usman   82    Karachi     82         82

In [176]:
a = pd.Series([23,34,565,343,23])
a.apply(lambda x:x**2)

0       529
1      1156
2    319225
3    117649
4       529
dtype: int64

In [177]:
s['Age_Group'] = pd.cut(s['Age'] , bins=3, labels=["Child", "Adult", "OverAge"])

In [178]:
s['Age_Group']

0    OverAge
1    OverAge
2      Child
3    OverAge
4    OverAge
Name: Age_Group, dtype: category
Categories (3, str): ['Child' < 'Adult' < 'OverAge']